application:
  name: Job-DatabaseFileTransfer (Spring Batch)
  full-name: Database File Transfer
  channel: SYSTEM
  organization: NEO JSC
  version: 1.0
  company: NEO JSC
  team: SMSC Team
  author: ManhND
  create-date: 01/01/2024
server:
app:
  file:
    format:
    path:
logging:
#  config: config/log4j2.xml
  job:
    sql-insert: insert into log_api_mt (sys_id,tsa_ip,tsa_acc,tsa_mty,tsa_mid,tda_ip,tda_acc,tda_mty,tda_mid,mti,smid,oa,oamnp,da,damnp,srr,mcl,dcs,status,rt,udl,ud,date_req,time_pro,json_req,json_res,req_org,res_org,cmd,trans_id,msg,num_msg,message_id) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,str_to_date(?,'%Y/%m/%d %H:%i:%s'),?,?,?,?,?,?,?,?,?,?)
    batch-size: 5000
    max-retry: 3
    path:
      time-read: 10000
      file-pattern: work-log-inbound*.log
      wait: logs/work/wait
      retry: logs/work/retry
      failed: logs/work/failed
spring:
  task:
    scheduling:
      pool:
        size: 10
  main:
    banner-mode: console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/smsc?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: false
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: ${application.name}
    data-source-properties: v$session.program=${application.name}
  datasource-log:
    jdbc-url: jdbc:mysql://localhost:3306/log?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: false
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: ${application.name}
    data-source-properties: v$session.program=${application.name}
